/**
 * Formats a lesson object into a Markdown string suitable for export.
 * Strips inline math delimiters ($...$) for plain-text readability.
 */
function stripMath(text) {
  if (!text) return ''
  // Replace $...$ with the inner content (no delimiters)
  return text.replace(/\$([^$]+)\$/g, '$1')
}

export function formatLessonMarkdown(lesson) {
  const lines = []

  lines.push(`# ${lesson.title}`)
  lines.push('')

  lesson.steps.forEach((step, i) => {
    lines.push(`## Step ${i + 1}: ${step.title}`)
    lines.push('')
    lines.push(stripMath(step.explanation))

    if (step.formula) {
      lines.push('')
      lines.push(`**Formula:** \`${step.formula}\``)
    }

    if (step.visual) {
      lines.push('')
      lines.push('```')
      lines.push(step.visual)
      lines.push('```')
    }

    if (step.tip) {
      lines.push('')
      lines.push(`> **Tip:** ${stripMath(step.tip)}`)
    }

    lines.push('')
    lines.push('---')
    lines.push('')
  })

  lines.push('## Final Answer')
  lines.push('')
  lines.push(stripMath(lesson.final_answer))

  if (lesson.real_world) {
    lines.push('')
    lines.push('---')
    lines.push('')
    lines.push('## In the Real World')
    lines.push('')
    lines.push(stripMath(lesson.real_world))
  }

  lines.push('')
  lines.push('---')
  lines.push('')
  lines.push('*Generated by WiseLab*')

  return lines.join('\n')
}

export function downloadLesson(lesson) {
  const text = formatLessonMarkdown(lesson)
  const blob = new Blob([text], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  const slug = lesson.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)
  a.href = url
  a.download = `wiselab-${slug}.md`
  a.click()
  URL.revokeObjectURL(url)
}

export async function copyLesson(lesson) {
  const text = formatLessonMarkdown(lesson)
  await navigator.clipboard.writeText(text)
}
